export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const RETRIEVE_EMPLOYEES = "RETRIEVE_EMPLOYEES";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_ALL_EMPLOYEES = "DELETE_ALL_EMPLOYEES";

export const CREATING_EMPLOYEE = "CREATING_EMPLOYEE";
export const RETRIEVING_EMPLOYEES = "RETRIEVING_EMPLOYEES";
export const UPDATING_EMPLOYEE = "UPDATING_EMPLOYEE";
export const DELETING_EMPLOYEE = "DELETING_EMPLOYEE";
export const DELETING_ALL_EMPLOYEES = "DELETING_ALL_EMPLOYEES";